CREATE TABLE TB_BUSINESS_OBJECT (
    BO_NR_IDENTITY           NUMBER(14,0) PRIMARY KEY,
	BO_ST_DESCRIPTION	     NVARCHAR2(200),
	BO_ST_CORRELATION_ID     NVARCHAR2(100),
	BO_ST_MAIN_DATA          NVARCHAR2(200),
	BO_ST_OPTION             NVARCHAR2(100),
	BO_TP_CONVERSION_STATUS  NVARCHAR2(100),
	BO_ID_CHANNEL            NVARCHAR2(100),
	BO_ST_STEP_CODE          NVARCHAR2(100),
	BO_ST_NETWORK_IP_ADDRESS NVARCHAR2(50),
	BO_DT_INSERTION_DATE     TIMESTAMP
);

CREATE SEQUENCE BUS_OBJ_SEQ START WITH 1 INCREMENT BY 1 NOCACHE CYCLE MINVALUE 1 MAXVALUE 99999999;
